config/routes.rb
Rails.application.routes.draw do
  resources :seasons

  resources :styles

  resources :upcodes

  root 'styles#index'

end

app/models/season.rb
class Season
  include Mongoid::Document
  field :name, type: String

  has_many :styles
end

app/models/style.rb
class Style
  include Mongoid::Document
  field :styleno, type: String
  field :year, type: Integer
  field :styleupcode, type: String
  
  belongs_to :season
  belongs_to :upcode

  validates_presence_of :styleno, :year, :styleupcode, :season_id, :upcode_id
end

app/models/upcode.rb
class Upcode
  include Mongoid::Document
  field :upc, type: String

  has_one :style
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name, :style_id)
    end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:styleno, :year, :season_id, :upcode_id, :styleupcode)
    end
end

app/controllers/upcodes_controller.rb
class UpcodesController < ApplicationController
  before_action :set_upcode, only: [:show, :edit, :update, :destroy]

  # GET /upcodes
  # GET /upcodes.json
  def index
    @upcodes = Upcode.all
  end

  # GET /upcodes/1
  # GET /upcodes/1.json
  def show
  end

  # GET /upcodes/new
  def new
    @upcode = Upcode.new
  end

  # GET /upcodes/1/edit
  def edit
  end

  # POST /upcodes
  # POST /upcodes.json
  def create
    @upcode = Upcode.new(upcode_params)

    respond_to do |format|
      if @upcode.save
        format.html { redirect_to @upcode, notice: 'Upcode was successfully created.' }
        format.json { render :show, status: :created, location: @upcode }
      else
        format.html { render :new }
        format.json { render json: @upcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upcodes/1
  # PATCH/PUT /upcodes/1.json
  def update
    respond_to do |format|
      if @upcode.update(upcode_params)
        format.html { redirect_to @upcode, notice: 'Upcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @upcode }
      else
        format.html { render :edit }
        format.json { render json: @upcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upcodes/1
  # DELETE /upcodes/1.json
  def destroy
    @upcode.destroy
    respond_to do |format|
      format.html { redirect_to upcodes_url, notice: 'Upcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upcode
      @upcode = Upcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upcode_params
      params.require(:upcode).permit(:upc, :style_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/upcodes_helper.rb
module UpcodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeuxluxUpc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<h1>Listing seasons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= season.name %></td>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
        <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @season.name %>
</p>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :styleno %><br>
    <%= f.text_field :styleno %>
  </div>
  <div class="field">
    Season<br>
    <%= f.collection_select :season_id, Season.all, :id, :name, include_blank: "Select season" %>
    <%= f.select :year, 2006..Time.now.year %>
    </div>
  <div class="field"> 
    UPC Code <br>
    <%= f.collection_select :styleupcode, Upcode.all, :upc, :upc, include_blank: "Select upcode" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<h1>Listing styles</h1>

<table>
  <thead>
    <tr>
      <th>Style Number</th>
      <th>Season</th>
      <th>UPC</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= style.styleno %></td>
        <td><%= style.season.name %> <%= style.year %></td>
        <td><%= style.styleupcode %></td>
        <td><%= link_to 'Show', style %></td>
        <td><%= link_to 'Edit', edit_style_path(style) %></td>
        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Styleno:</strong>
  <%= @style.styleno %>
</p>

<p>
  <strong>Season:</strong>
  <%= @style.season.name %>
  <%= @style.year %>
  <%#= @style.calendar.season %> <%#= @style.calendar.year %>
</p>

<p>
  <strong>UPC:</strong>
  <%= @style.styleupcode %>
</p>


<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>

app/views/upcodes/_form.html.erb
<%= form_for(@upcode) do |f| %>
  <% if @upcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upcode.errors.count, "error") %> prohibited this upcode from being saved:</h2>

      <ul>
      <% @upcode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :upc %><br>
    <%= f.text_field :upc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

 

app/views/upcodes/edit.html.erb
<h1>Editing upcode</h1>

<%= render 'form' %>

<%= link_to 'Show', @upcode %> |
<%= link_to 'Back', upcodes_path %>

app/views/upcodes/index.html.erb
<h1>Listing upcodes</h1>

<table>
  <thead>
    <tr>
      <th>Upc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upcodes.each do |upcode| %>
      <tr>
        <td><%= upcode.upc %></td>
        <td><%= link_to 'Show', upcode %></td>
        <td><%= link_to 'Edit', edit_upcode_path(upcode) %></td>
        <td><%= link_to 'Destroy', upcode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upcode', new_upcode_path %>

app/views/upcodes/new.html.erb
<h1>New upcode</h1>

<%= render 'form' %>

<%= link_to 'Back', upcodes_path %>

app/views/upcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Upc:</strong>
  <%= @upcode.upc %>
</p>

<%= link_to 'Edit', edit_upcode_path(@upcode) %> |
<%= link_to 'Back', upcodes_path %>